{
    'name': 'Matracon Fleet Management',
    'version': '1.0.0',
    'summary': 'Fleet & Vehicle Management — MPPL coding, site-scoped costs, GL integration, and dashboard',
    'author': 'Matracon Pakistan',
    'category': 'Operations/Fleet',
    'depends': [
        'fleet',
        'site_operations',
        'purchase_demand_raise',
        'stock',
        'account',
        'analytic',
    ],
    'data': [
        'security/app_visibility_fleet.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'data/fleet_categories_data.xml',
        'data/fleet_service_types_data.xml',
        'views/fleet_settings_views.xml',
        'views/fleet_vehicle_ext_views.xml',
        'views/fleet_log_entry_ext_views.xml',
        'views/fleet_spare_part_views.xml',
        'views/fleet_vehicle_ledger_views.xml',
        'views/fleet_vehicle_trip_views.xml',
        'views/management_dashboard_fleet_views.xml',
        'views/site_store_dashboard_fleet_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
