{
    'name': 'Site Operations',
    'version': '1.7.5',
    'summary': 'Material Issuance, Finance HO, Compliance (BG & Tax Notices), Attendance & Petty Cash',
    'author': 'Matracon Pakistan',
    'depends': [
        'purchase_demand_raise',
        'project',
        'account',
        'stock',
        'mail',
        'analytic',
        'purchase',
        'project_todo',
        'contacts',
        'hr',
        'hr_attendance',
    ],
    'data': [
        'security/app_visibility_groups.xml',
        'security/security_groups.xml',
        'security/role_app_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'security/purchase_record_rules.xml',
        'data/account_configuration_data.xml',
        'data/bank_journals_data.xml',
        'data/site_config_data.xml',
        'data/site_warehouses_data.xml',
        'data/petty_cash_sequence.xml',
        'data/compliance_sequences.xml',
        'data/ipc_sequence.xml',
        'data/app_visibility_data.xml',
        'views/hr_employee_views.xml',
        'views/attendance_views.xml',
        'views/salary_views.xml',
        'views/petty_cash_views.xml',
        'views/bank_guarantee_views.xml',
        'views/tax_notice_views.xml',
        'views/management_dashboard_views.xml',
        'views/site_accountant_dashboard_views.xml',
        'views/project_project_views.xml',
        'views/material_issuance_form_views.xml',
        'views/backcharge_views.xml',
        'views/material_issuance_list_views.xml',
        'views/site_store_dashboard_views.xml',
        'views/liability_sheet_views.xml',
        'views/vendor_bill_views.xml',
        'views/vendor_payment_views.xml',
        'views/site_config_views.xml',
        'views/return_picking_views.xml',
        'views/partner_views.xml',
        'views/res_users_app_views.xml',
        'views/wht_certificate_views.xml',
        'views/postdated_cheque_views.xml',
        'views/cheque_series_views.xml',
        'views/subcontractor_ipc_views.xml',
        'views/material_cost_views.xml',
        'views/menus.xml',
        'report/mif_report.xml',
        'report/mif_report_template.xml',
        'report/mtn_report.xml',
        'report/mtn_report_template.xml',
        'report/cheque_report.xml',
        'report/cheque_report_template.xml',
        'report/liability_sheet_report.xml',
        'report/liability_sheet_template.xml',
        'report/salary_slip_report.xml',
        'report/employee_card_report.xml',
        'report/employee_card_template.xml',
        'report/wht_certificate_report.xml',
        'report/wht_certificate_template.xml',
        'report/subcontractor_ipc_report.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'post_migrate_hook': 'post_migrate_hook',
    'assets': {
        'web.assets_backend': [
            'site_operations/static/src/scss/matracon_payment_form.scss',
            'site_operations/static/src/scss/matracon_hr.scss',
            'site_operations/static/src/scss/matracon_management_dashboard.scss',
            'site_operations/static/src/js/attendance_grid_colors.js',
        ],
    },
    'demo': [
        'demo/demo_users.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
