{
    'name': 'Site Operations',
    'version': '1.0.6',
    'summary': 'Material Issuance, Returns, Site-to-Site Transfers, Liability Sheets, Finance HO Payments',
    'author': 'Matracon Pakistan',
    'depends': [
        'purchase_demand_raise',
        'project',
        'account',
        'stock',
        'mail',
        'analytic',
        'purchase',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'security/purchase_record_rules.xml',
        'data/account_configuration_data.xml',
        'data/site_config_data.xml',
        'views/project_project_views.xml',
        'views/material_issuance_form_views.xml',
        'views/material_issuance_list_views.xml',
        'views/site_store_dashboard_views.xml',
        'views/liability_sheet_views.xml',
        'views/vendor_payment_views.xml',
        'views/site_config_views.xml',
        'views/return_picking_views.xml',
        'views/partner_views.xml',
        'views/menus.xml',
        'report/mif_report.xml',
        'report/mif_report_template.xml',
        'report/liability_sheet_report.xml',
        'report/liability_sheet_template.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'demo': [
        'demo/demo_users.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
